const fs = require('fs');
const crypto = require('crypto');
const grunt = require('grunt');
const path = require('path');
const swPrecache = require('sw-precache');
const fakedomain = grunt.option('fakedomain');
const workboxBuild = require('workbox-build');
const domain = fakedomain ? 'http://localhost:3025/' : 'https://shishiv30.github.io/CUI/';
const generateSpriteConfig = function (imgDir) {
    imgDir = `s-${imgDir}`;

    function getCollectiveMd5(files) {
        const md5sum = crypto.createHash('md5');
        const expandedFiles = grunt.file.expand(files),
            collectiveContent = expandedFiles.reduce(function (content, file) {
                return content + fs.readFileSync(file, 'binary');
            }, '');
        md5sum.update(collectiveContent);
        return md5sum.digest('hex')
            .slice(0, 10);
    }
    const hash = getCollectiveMd5(`src/img/${imgDir}/*.png`);
    const imgName = `${imgDir}-${hash}`;
    return {
        src: `src/img/${imgDir}/*.png`,
        dest: `public/dist/src/img/autogenerated/${imgName}.png`,
        destCss: `src/scss/base/autogenerated/${imgDir}.scss`,
        imgPath: `img/autogenerated/${imgName}.png`,
        cssVarMap: function (sprite) {
            sprite.name = `${imgDir}-${sprite.name}`;
        },
        cssTemplate: 'src/scss/base/_sprites.scss.handlebars'
    };
};
module.exports = function (grunt) {
    // Project configuration.
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        sprite: ['img'].reduce((config, k) => Object.assign(config, {
            [k]: generateSpriteConfig(k)
        }), {}),
        workbox:{
            'default':{
                config:{
                    globPatterns: [
                        'dist/src/cui.lib.min.js',
                        'dist/src/cui.min.js',
                        'dist/src/cui.min.css',
                        'dist/src/img/*.{gif,png,jpg}',
                        'dist/src/img/autogenerated/*.{gif,png,jpg}',
                        'dist/src/fonts/*.{woff,ttf,svg,eot}',
                        'dist/src/doc/src/*.{js,ico,png,json,png,css}',
                        '*.html'
                    ],
                    globDirectory:'./public',
                    swSrc: 'workbox.sw.js',
                    swDest: './public/workbox.sw.js'
                },
                rootDir:'./public/',
                fileName:'sw3.js',
            }
        },
        swPrecache:{
            'default':{
                config:{
                    staticFileGlobs: [
                        './public/dist/src/cui.lib.min.js',
                        './public/dist/src/cui.min.js',
                        './public/dist/src/cui.min.css',
                        './public/dist/src/img/*.{gif,png,jpg}',
                        './public/dist/src/img/autogenerated/*.{gif,png,jpg}',
                        './public/dist/src/fonts/*.{woff,ttf,svg,eot}',
                        './public/dist/src/doc/src/*.{js,ico,png,json,png,css}',
                    ],
                    replacePrefix: domain,
                    stripPrefix: './public/'
                },
                rootDir:'./public/',
                fileName:'sw2.js',
            }
        },
        'sw-precache': {
            options: {
                cacheId: '<%= pkg.name %>',
                baseDir: './public/',
                workerFileName: 'sw.js',
                verbose: false,
            },
            'default': {
                staticFileGlobs: [
                    'dist/src/cui.lib.min.js',
                    'dist/src/cui.min.js',
                    'dist/src/cui.min.css',
                    'dist/src/img/*.{gif,png,jpg}',
                    'dist/src/img/autogenerated/*.{gif,png,jpg}',
                    'dist/src/fonts/*.{woff,ttf,svg,eot}',
                    'dist/src/doc/src/*.{js,ico,png,json,png,css}',
                ],
                replacePrefix: domain,
                stripPrefix: './public/',
            }
        },
        htmlmin: { // Task
            dist: { // Target
                options: { // Target options
                    removeComments: true,
                    collapseWhitespace: true
                },
                files: { // Dictionary of files
                    'public/index.html': 'public/index.html',
                }
            }
        },
        sass: {
            options: {
                outputStyle: 'expanded'
            },
            dist: {
                files: [{
                    'public/dist/src/cui.min.css': 'src/scss/cui.scss'
                }]
            }
        },
        concat: {
            options: {
                separator: '\n'
            },
            dist: {
                files: [{
                    src: ['src/js/plugins/*.js'],
                    dest: 'public/dist/src/<%= pkg.name %>.min.js'
                }, {
                    src: ['src/js/libs/*.js'],
                    dest: 'public/dist/src/<%= pkg.name %>.lib.min.js'
                }]
            }
        },
        copy: {
            dist: {
                files: [{
                    expand: true,
                    cwd: 'src/',
                    src: ['img/*.*', 'img/pin/*.*', 'fonts/*.*', 'doc/src/*.*'],
                    dest: 'public/dist/src/'
                }, {
                    expand: true,
                    cwd: '',
                    src: ['favicon.ico'],
                    dest: 'public'
                }]
            }
        },
        autoprefixer: {
            dist: {
                files: {
                    'public/dist/src/<%= pkg.name %>.min.css': 'public/dist/src/<%= pkg.name %>.min.css'
                }
            }
        },
        cssmin: {
            dist: {
                files: [{
                    src: ['public/dist/src/<%= pkg.name %>.min.css'],
                    dest: 'public/dist/src/<%= pkg.name %>.min.css'
                }]
            }
        },
        uglify: {
            dist: {
                files: [{
                    src: ['public/dist/src/<%= pkg.name %>.lib.min.js'],
                    dest: 'public/dist/src/<%= pkg.name %>.lib.min.js'
                }, {
                    src: ['public/dist/src/<%= pkg.name %>.min.js'],
                    dest: 'public/dist/src/<%= pkg.name %>.min.js'
                }]
            }
        },
        watch: {
            script: {
                files: ['src/js/plugins/*.js', 'src/doc/src/*.js'],
                tasks: ['concat:dist', 'copy']
            },
            scss: {
                files: ['src/scss/*.scss', 'src/scss/**/*.scss', 'src/doc/src/*.css'],
                tasks: ['sass', 'copy']
            },
            css: {
                options: {
                    debounceDelay: 250,
                    livereload: true
                },
                files: ['public/dist/src/*.css'],
                task: ['autoprefixer']
            }
        },
        replace: {
            publish: {
                src: [
                    'public/index.html'
                ],
                overwrite: true,
                replacements: [{
                    from: '%RootUrl%',
                    to: 'https://shishiv30.github.io/CUI/'
                }]
            },
            dev: {
                src: [
                    'public/index.html'
                ],
                overwrite: true,
                replacements: [{
                    from: '%RootUrl%',
                    to: 'http://localhost:3025/'
                }]
            }
        }
    });
    grunt.registerMultiTask('swPrecache', function() {
        var done = this.async();
        var rootDir = this.data.rootDir;
        var fileName =this.data.fileName;
        var config = this.data.config;
        console.log(JSON.stringify(path.join(rootDir, fileName)));
        swPrecache.write(path.join(rootDir, fileName), config, function(error){
            if (error) {
                grunt.fail.warn(error);
            }
            done();
        });
    });
    grunt.registerMultiTask('workbox', function() {
        var done = this.async();
        var config = this.data.config;
        workboxBuild.injectManifest(config);
        done();
    });

    grunt.loadNpmTasks('grunt-text-replace');
    grunt.loadNpmTasks('grunt-sw-precache');
    grunt.loadNpmTasks('grunt-contrib-htmlmin');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-autoprefixer');
    grunt.loadNpmTasks('grunt-spritesmith');
    grunt.loadNpmTasks('grunt-sass');
    grunt.registerTask('default', ['copy', 'concat', 'sprite', 'sass', 'autoprefixer', 'cssmin', 'uglify', 'htmlmin','replace:publish','workbox']);
    grunt.registerTask('dev', ['copy', 'concat', 'sprite', 'sass', 'autoprefixer','replace:dev', 'workbox', 'watch']);
};
